#!/bin/sh
#BIN=./node_modules/.bin
#npm run styles
#NODE_ENV=production $BIN/webpack -p
#$BIN/uglifyjs app/js/main.js  --mangle --compress warnings=false > app/js/min.js
#mv app/js/min.js app/js/main.js
node app.js

