#!/bin/sh
#mkdir -p public/js
NODE_ENV=production node_modules/.bin/webpack -p
node_modules/.bin/uglifyjs app/js/main.js  --mangle --compress warnings=false > app/js/min.js
mv public/js/min.js public/js/main.js
node app.js

